### ISSUE TITLE
Styling questions, and problems closing the range input

### ISSUE THREAD

**Issue by oyeanuj** [Dishant15/react-datetime-range-super-picker#10]
Hi @Dishant15, thanks for creating this excellent library! As I was giving this a try, I ran into a couple of issues that acted as a blocker that I thought I should mention to see if they were on your radar:

1. Clicking on 'Done' on the range picker doesn't seem to close the picker. If the 'To date' is active, then it just switches to the 'from date'. This unfortunately acted as a blocker as it wasn't possible to proceed on our form.

2. Styling options: I'm curious if you are planning on creating ways to customize the styling. I overwrote the CSS variables for the colors but even them, it was hard to customize color on picker headers, for example, which had hardcoded colors. I'd love a way to customize border-radius, height, width, font-size, etc.

Thank you!

**Comment by Dishant15** [comment]
Hey @oyeanuj, glad that you liked this library.

1. I guess you are talking about "DateTimeRangePickerInput" component that has "Done" handler. In that case it is working perfectly for me and also in the demo link of current version. If that is not the case for you can you please show me some code about how you are using this component in your project. If that does not work for you there is also "DateTimeRangePicker" component that you can use and handle when to show/hide it with your internal state logic.

2. You will not have to wait long for custom styling. It is already 90% done but under testing at the moment. We will be launching that update with theme support. Having "dark" and "light" theme out of the box and than you can customise only the colours you want to change or all of the theme colours.

I hope this library will be great addition to your project !!
