### ISSUE TITLE
Module not found: Can't resolve 'date-fns' 

### ISSUE THREAD

**Issue by HARSHVDARJI** [Dishant15/react-datetime-range-super-picker#5]
Hello,

I create new project using
npx create-react-app superpicker

install your package and get error
Module not found: Can't resolve 'date-fns' in '/home/harsh/project/current/testing/superpicker/node_modules/react-datetime-range-super-picker/dist'

**Comment by atuls45** [comment]
What's the solution for this issue?

**Comment by Dishant15** [comment]
@atuls45 we have moved date-fns as external dependancy to optimise library size and functionality.
All you need to do is run 
"yarn add date-fns" 
this will install date-fns in your project
